
---------------------------------------- TẠO CÁC TRIGGER ----------------------------------------
--BENH NHAN
GO
CREATE TRIGGER TRIGGER_BN
ON BENHNHAN
FOR INSERT
AS
	BEGIN
		IF EXISTS (SELECT * FROM inserted I, BENHNHAN BN WHERE I.MABENHNHAN = BN.MABENHNHAN AND
				   I.HOTEN LIKE '%[0-9]%')
				   BEGIN
					RAISERROR('HOTEN KHONG THE CHUA KY TU SO', 16, 1)--HỌ TÊN KHÔNG THỂ CÓ KÍ TỰ SỐ 
					ROLLBACK TRANSACTION					
				   END
        IF EXISTS (SELECT * FROM inserted I, BENHNHAN BN WHERE I.MABENHNHAN = BN.MABENHNHAN AND
				   ISNUMERIC(I.SODIENTHOAI) = 0)
				   BEGIN
					RAISERROR('SODIENTHOAI KHONG THE CHUA CHU CAI', 16, 1)--SỐ ĐIỆN THOẠI KHÔNG THỂ CÓ CHỮ CÁI
					ROLLBACK TRANSACTION					
				   END
	END
GO  

--THONGTINTHANHTOAN
---------------------------------------------------------------------------------
CREATE TRIGGER TRIGGER_THONGTINTT_TONGTIEN --TRIGGER CHO BẢNG THÔNG TIN THANH TOÁN ĐỂ TÍNH TỔNG TIỀN ĐIỀU TRỊ DỰA TRÊN BẢNG HÓA ĐƠN THANH TOÁN
ON THONGTINTHANHTOAN
FOR INSERT
AS
    BEGIN
        IF EXISTS (SELECT * FROM inserted I, THONGTINTHANHTOAN T WHERE I.MATHANHTOAN = T.MATHANHTOAN AND I.NGAYGIAODICH < I.NGAYTHANHTOAN) 
            BEGIN   
                UPDATE T
                SET T.TONGTIENTHANHTOAN = 0
                FROM THONGTINTHANHTOAN T JOIN INSERTED I ON I.MATHANHTOAN = T.MATHANHTOAN 
                  
                UPDATE T2
                SET T2.TIENTHOI = 0
                FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MATHANHTOAN
  --PHẦN NÀY ĐỂ KIỂM TRA MỖI LẦN THÊM MỘT THÔNG TIN THANH TOÁN, ĐẢM BẢO PHẦN TIỀN THANH TOÁN TRONG BẢNG HỒ SƠ CHI TIẾT BỆNH NHÂN CŨNG ĐƯỢC UPDATE
                IF EXISTS (SELECT * FROM THONGTINTHANHTOAN T JOIN CHITIETHOSOBENHNHAN CTHS ON CTHS.MABENHNHAN = T.MABENHNHAN JOIN INSERTED I ON I.MATHANHTOAN = T.MATHANHTOAN)
                        BEGIN
                            UPDATE CTHSBN
                            SET CTHSBN.DATHANHTOAN = CTHSBN.DATHANHTOAN + T.TONGDATRA
                            FROM CHITIETHOSOBENHNHAN CTHSBN JOIN (SELECT CTHSBN2.MABENHNHAN, SUM(i2.TIENDATRA) AS TONGDATRA
                                                                FROM inserted i2 JOIN CHITIETHOSOBENHNHAN CTHSBN2 ON CTHSBN2.MABENHNHAN = i2.MABENHNHAN
                                                                GROUP BY CTHSBN2.MABENHNHAN) AS T ON CTHSBN.MABENHNHAN = T.MABENHNHAN
                            
                        END
            END
        ELSE 
            BEGIN
                RAISERROR('NGAY THANH TOAN PHAI LON HON NGAY GIAO DICH', 16, 1)--SỐ ĐIỆN THOẠI KHÔNG THỂ CÓ CHỮ CÁI
				ROLLBACK TRANSACTION
            END
    END
GO


--TRIGGER KIỂM TRA LỊCH HẸN CÓ TRÙNG VỚI CÁC LỊCH KHÁC CỦA BỆNH NHÂN HOẶC BÁC SĨ KHÔNG
CREATE TRIGGER TRIGGER_LICHHEN 
ON LICHHEN
INSTEAD OF INSERT
AS
	BEGIN
    SET NOCOUNT ON

		IF EXISTS (SELECT * FROM inserted I INNER JOIN LICHHEN LH ON (I.MABENHNHAN = LH.MABENHNHAN OR I.NHASI = LH.NHASI) AND ((DATEDIFF(DAY, I.THOIGIAN, LH.GIOKETTHUC) > 0) OR (DATEDIFF(DAY, LH.THOIGIAN, I.GIOKETTHUC) < 0)) AND I.NGAYHENYEUCAU = LH.NGAYHENYEUCAU)
			BEGIN
					RAISERROR('LICH HEN KHONG DUOC TRUNG VOI LICH CUA BENH NHAN HOAC NHA SI', 16, 1)--HỌ TÊN KHÔNG THỂ CÓ KÍ TỰ SỐ 
					ROLLBACK TRANSACTION	
			END
        ELSE
            BEGIN
                    INSERT INTO LICHHEN(MALICHHEN, THOIGIAN, GIOKETTHUC, NHASI, MABENHNHAN,  THOIGIANYEUCAU, NGAYHENYEUCAU, PHONG, TINHTRANG, GHICHU)
                    SELECT MALICHHEN, THOIGIAN, GIOKETTHUC, NHASI, MABENHNHAN,  THOIGIANYEUCAU, NGAYHENYEUCAU, PHONG, TINHTRANG, GHICHU
                    FROM inserted
            END
	END
GO

--TÍNH TUỔI TRÊN BẢNG CHI TIẾT HSBN
CREATE TRIGGER TRIGGER_TINHTUOI
ON CHITIETHOSOBENHNHAN
FOR INSERT
AS
    BEGIN
        IF EXISTS (SELECT * FROM inserted I, BENHNHAN BN WHERE I.MABENHNHAN = BN.MABENHNHAN)
            BEGIN
                UPDATE CTHSBN
                SET CTHSBN.TUOI = DATEDIFF(YY, BN.NGAYSINH, GETDATE())
                FROM BENHNHAN BN JOIN CHITIETHOSOBENHNHAN CTHSBN ON CTHSBN.MABENHNHAN = BN.MABENHNHAN
            END
    END
GO

--TÍNH TỔNG TIỀN ĐIỀU TRỊ TRÊN BẢNG CHITIETHOSOBENHNHAN
CREATE TRIGGER TRIGGER_HSCTBN_TINHTIEN 
ON CHITIETHOSOBENHNHAN
FOR INSERT
AS
    BEGIN
        
        UPDATE CTHSBN
        SET CTHSBN.TONGTIENDIEUTRI = 0
        FROM CHITIETHOSOBENHNHAN CTHSBN JOIN INSERTED I ON I.MABENHNHAN = CTHSBN.MABENHNHAN 

        UPDATE CTHSBN
        SET CTHSBN.DATHANHTOAN = 0
        FROM CHITIETHOSOBENHNHAN CTHSBN JOIN INSERTED I ON I.MABENHNHAN = CTHSBN.MABENHNHAN 
                    
    END
GO



--UPDATE LẠI GIÁ TRỊ TỔNG TIỀN THANH TOÁN CỦA BẢNG THÔNG TIN THANH TOÁN MỖI KHI HÓA ĐƠN TƯƠNG ỨNG VỚI THANH TOÁN NÀY ĐƯỢC NHẬP
CREATE TRIGGER TRIGGER_HOADONDIEUTRI
ON HOADONDIEUTRI
FOR INSERT
AS
    BEGIN
        --UPDATE LẠI GIÁ TRỊ TỔNG TIỀN CẦN THANH TOÁN TRONG THÔNG TIN THANH TOÁN LUÔN
        IF EXISTS (SELECT * FROM inserted I, HOADONDIEUTRI HD WHERE I.MAHOADON = HD.MAHOADON)
            BEGIN
                IF EXISTS (SELECT * FROM THONGTINTHANHTOAN T JOIN HOADONDIEUTRI HD ON HD.MAHOADON = T.MATHANHTOAN JOIN INSERTED I ON I.MAHOADON = T.MATHANHTOAN)
                    BEGIN
                        UPDATE T
                        SET T.TONGTIENTHANHTOAN = T.TONGTIENTHANHTOAN + TONGTHANHTOAN
                        FROM THONGTINTHANHTOAN T JOIN (SELECT i.MAHOADON, SUM(i.PHIDIEUTRI) AS TONGTHANHTOAN
                                                    FROM inserted i
                                                    GROUP BY i.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN      
                    END
            END
        --UPDATE LẠI GIÁ TRỊ TỔNG TIỀN CẦN THANH TOÁN TRONG HỒ SƠ CHI TIẾT BỆNH NHÂN LUÔN
        IF EXISTS (SELECT * FROM THONGTINTHANHTOAN T JOIN CHITIETHOSOBENHNHAN CTHS ON CTHS.MABENHNHAN = T.MABENHNHAN JOIN INSERTED I ON T.MATHANHTOAN = I.MAHOADON)
            BEGIN
                -- -- --O DAY
                UPDATE CTHSBN
                SET CTHSBN.TONGTIENDIEUTRI = CTHSBN.TONGTIENDIEUTRI + TONGTHANHTOAN
                FROM CHITIETHOSOBENHNHAN CTHSBN JOIN THONGTINTHANHTOAN T ON T.MABENHNHAN = CTHSBN.MABENHNHAN
                                            JOIN (SELECT i.MAHOADON, SUM(i.PHIDIEUTRI) AS TONGTHANHTOAN
                                            FROM inserted i
                                            GROUP BY i.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN
            END

        -- TỰ ĐỘNG TÍNH TIỀN THỐI DỰA TRÊN TIỀN CẦN THANH TOÁN VÀ TIỀN ĐÃ TRẢ NẾU TIỀN ĐÃ TRẢ LỚN HƠN TIỀN THANH TOÁN
       
        UPDATE T2
        SET T2.TIENTHOI = T2.TIENDATRA - T2.TONGTIENTHANHTOAN
        FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MAHOADON
        WHERE T2.TONGTIENTHANHTOAN < T2.TIENDATRA
                    
        
        UPDATE T2
        SET T2.TIENTHOI = 0
        FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MAHOADON
        WHERE T2.TONGTIENTHANHTOAN >= T2.TIENDATRA
        
    END
GO

-- SELECT * FROM CHITIETHOSOBENHNHAN WHERE MABENHNHAN = '000693'
-- SELECT * FROM THONGTINTHANHTOAN WHERE MABENHNHAN = '000693'
-- SELECT * FROM HOADONDIEUTRI WHERE WHERE MABENHNHAN = '000693'
-- SELECT * FROM DIEUTRI


-- INSERT DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES ('001', 'E')

-- SELECT TOP 1 * FROM NHASI

-- INSERT DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES ('005', 'E')
-- INSERT DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES ('002', 'E')
-- INSERT INTO HOADONDIEUTRI(MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
-- VALUES ('606762', '005', 'afhbd', '21/12/2022', 4000)
-- INSERT INTO HOADONDIEUTRI(MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
-- VALUES ('606762', '002', 'DEO CO MO TA', '21/12/2022', 10)
-- INSERT INTO THONGTINTHANHTOAN(MATHANHTOAN,NHASI,MABENHNHAN,NGAYTHANHTOAN,NGAYGIAODICH,TONGTIENTHANHTOAN,TIENDATRA,TIENTHOI,LOAITHANHTOAN)
-- VALUES ('606763', '170902', '871991', '31/05/2004', '13/05/1986',100,200,100,'THANH TOÁN ONLINE')
-- INSERT INTO HOADONDIEUTRI(MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
-- VALUES ('606763', '005', 'DEO CO MO TA', '21/12/2022', 4000)
-- INSERT INTO HOADONDIEUTRI(MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
-- VALUES ('606763', '002', 'DEO CO MO TA', '21/12/2022', 10)
-- UPDATE T
-- SET T.TONGTIENTHANHTOAN = 6
-- FROM THONGTINTHANHTOAN T

-- UPDATE T
-- SET T.TONGTIENTHANHTOAN = T.TONGTIENTHANHTOAN + TONGTHANHTOAN
-- FROM THONGTINTHANHTOAN T JOIN (SELECT i.MAHOADON, SUM(i.PHIDIEUTRI) AS TONGTHANHTOAN
--                                                     FROM HOADONDIEUTRI i
--                                                     GROUP BY i.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN
-- SELECT * FROM THONGTINTHANHTOAN       