USE QLNhaKhoa
GO

create PROCEDURE InsertSampleData
AS
BEGIN
	
	WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng NGUOIDUNG với NGAYSINH nhỏ hơn ngày hiện tại
		INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
		SELECT 
			k AS MANGUOIDUNG,
			'user_' + CAST(k AS VARCHAR) AS TENDANGNHAP,
			'password_' + CAST(k AS VARCHAR) AS MATKHAU,
			'User ' + CAST(k AS VARCHAR) AS TENNGUOIDUNG,
			DATEADD(DAY, -FLOOR(RAND() * 36525), GETDATE()) AS NGAYSINH,
			N'Địa chỉ ' + CAST(k AS VARCHAR) AS DIACHI,
			'432' + RIGHT('0000' + CAST(k AS VARCHAR), 4) AS SODIENTHOAI,
			N'NHA SĨ' AS ROLES
		FROM Nums
		WHERE k <= 100000;
	
	SET IDENTITY_INSERT NGUOIDUNG OFF
    PRINT 'Sample data inserted successfully.'
END
GO

create PROCEDURE InsertSampleData_BenhNhan
AS
BEGIN
    WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng BENHNHAN với NGAYSINH nhỏ hơn ngày hiện tại
		INSERT INTO BENHNHAN (MABENHNHAN, HOTEN, SODIENTHOAI, DIACHI, EMAIL, NGAYSINH, NHASI)
		SELECT 
			k as MABENHNHAN,
			'Benh nhan ' AS HOTEN,
			'098' + RIGHT('0000' + CAST(k AS VARCHAR), 4) AS SODIENTHOAI,
			'Dia chi ' + CAST(k AS VARCHAR) AS DIACHI,
			'email_' + CAST(k AS VARCHAR) + '@example.com' AS EMAIL,
			DATEADD(DAY, -FLOOR(RAND() * 36525), GETDATE()) AS NGAYSINH,
			CASE WHEN k % 5 = 0 THEN NULL ELSE k % 5 + 1 END AS NHASI
		FROM Nums
		WHERE k <= 100000;
	

    PRINT 'Sample data inserted successfully.'
END
GO

create PROCEDURE InsertSampleData_NhaSi
AS
BEGIN
    WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng NHASI
		INSERT INTO NHASI (MABACSI, CHUYENMON, KINHNGHIEM)
		SELECT 
			k AS MABACSI,
			'Chuyen mon ' + CAST(k AS VARCHAR) AS CHUYENMON,
			'Kinh nghiem ' + CAST(k AS VARCHAR) + ' nam' AS KINHNGHIEM
		FROM Nums
		WHERE k <= 100000;
	
    PRINT 'Sample data inserted successfully.'
END
GO


create PROCEDURE InsertSampleData_ChiTietBenhNhan
AS
BEGIN
    WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng CHITIETHOSOBENHNHAN với MABENHNHAN từ 1 đến 1000000
		INSERT INTO CHITIETHOSOBENHNHAN (MABENHNHAN, TUOI, GIOITINH, TONGTIENDIEUTRI, DATHANHTOAN, SUCKHOERANGMIENG, TINHTRANGDIUNG)
		SELECT 
			k AS MABENHNHAN,
			null,
			CASE WHEN k % 2 = 0 THEN N'NAM' ELSE N'NỮ' END AS GIOITINH,
			null, -- Giả sử mỗi bệnh nhân có chi phí điều trị là k * 100000
			null, -- Giả sử một nửa bệnh nhân đã thanh toán
			N'Sức khỏe răng miệng ' + CAST(k AS VARCHAR) AS SUCKHOERANGMIENG,
			N'Tình trạng điều ng ' + CAST(k AS VARCHAR) AS TINHTRANGDIUNG
		FROM Nums
		WHERE k <= 100000;

    END

    PRINT 'Sample data inserted successfully.'
GO

create PROCEDURE InsertSampleData_Thuoc
AS
BEGIN
    WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng THUOC với MATHUOC từ 1 đến 1000000
		INSERT INTO THUOC (MATHUOC, TENTHUOC, GHICHU)
		SELECT 
			k AS MATHUOC,
			N'Thuốc ' + CAST(k AS VARCHAR) AS TENTHUOC,
			N'Ghi chú cho thuốc ' + CAST(k AS VARCHAR) AS GHICHU
		FROM Nums
		WHERE k <= 100000;

	END
    PRINT 'Sample data inserted successfully.'
GO

create PROCEDURE InsertSampleData_ChongChiDinh
AS
BEGIN
   WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng CHONGCHIDINH với MABENHNHAN và MATHUOC từ 1 đến 1000000
		INSERT INTO CHONGCHIDINH (MABENHNHAN, MATHUOC)
		SELECT 
			k AS MABENHNHAN,
			k AS MATHUOC
		FROM Nums
		WHERE k <= 100000;


	END
    PRINT 'Sample data inserted successfully.'
GO


create PROCEDURE InsertSampleData_DonThuoc
AS
BEGIN
   WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng CHITIETDONTHUOC với MADONTHUOC và MATHUOC từ 1 đến 1000000
		INSERT INTO DONTHUOC (MADONTHUOC, KEHOACHDIEUTRI)
		SELECT 
			k AS MADONTHUOC,
			k AS KEHOACHDIEUTRI
		FROM Nums
		WHERE k <= 100000;



	END
    PRINT 'Sample data inserted successfully.'
GO

create PROCEDURE InsertSampleData_ChiTietDonThuoc
AS
BEGIN
   WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng CHITIETDONTHUOC với MADONTHUOC và MATHUOC từ 1 đến 1000000
		INSERT INTO CHITIETDONTHUOC (MADONTHUOC, MATHUOC, LIEULUONG, CHIDINH)
		SELECT 
			k AS MADONTHUOC,
			k AS MATHUOC,
			N'Liều lượng ' + CAST(k AS VARCHAR) AS LIEULUONG,
			N'Chỉ định ' + CAST(k AS VARCHAR) AS CHIDINH
		FROM Nums
		WHERE k <= 100000;



	END
    PRINT 'Sample data inserted successfully.'
GO


create PROCEDURE InsertSampleData_KeHoachDieuTri
AS
BEGIN
  WITH
	L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
	L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
	L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
	L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
	L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
	L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
	Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

	-- Thêm dữ liệu cho bảng KEHOACHDIEUTRI với MAKEHOACH, MABENHNHAN, MANHASI, MATROKHAM từ 1 đến 1000000
	INSERT INTO KEHOACHDIEUTRI (MAKEHOACH, MOTA, NGAYDIEUTRI, TINHTRANG, MABENHNHAN, MANHASI, MATROKHAM)
	SELECT 
		k AS MAKEHOACH,
		N'Mô tả cho kế hoạch ' + CAST(k AS VARCHAR) AS MOTA,
		DATEADD(DAY, k, GETDATE()) AS NGAYDIEUTRI,
		CASE WHEN k % 3 = 0 THEN N'KẾ HOẠCH' WHEN k % 3 = 1 THEN N'ĐÃ HOÀN THÀNH' ELSE N'ĐÃ HỦY' END AS TINHTRANG,
		k AS MABENHNHAN,
		k AS MANHASI,
		null AS MATROKHAM
	FROM Nums
	WHERE k <= 100000;



	END
    PRINT 'Sample data inserted successfully.'
GO


create PROCEDURE InsertSampleData_Rang
AS
BEGIN
 WITH
	L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
	L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
	L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
	L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
	L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
	L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
	Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

	-- Thêm dữ liệu cho bảng RANG với MAKEHOACH và RANG từ 1 đến 1000000
	INSERT INTO RANG (MAKEHOACH, RANG, BEMATRANG)
	SELECT 
		k AS MAKEHOACH,
		CASE WHEN k % 4 = 0 THEN N'RĂNG CỬA' WHEN k % 4 = 1 THEN N'RĂNG NANH' WHEN k % 4 = 2 THEN N'RĂNG HÀM NHỎ' ELSE N'RĂNG HÀM LỚN' END AS RANG,
		CASE WHEN k % 6 = 0 THEN N'LINGUAL' WHEN k % 6 = 1 THEN 'FACIAL' WHEN k % 6 = 2 THEN 'DISTAL' WHEN k % 6 = 3 THEN 'MESIAL' WHEN k % 6 = 4 THEN 'TOP' ELSE 'ROOT' END AS BEMATRANG
	FROM Nums
	WHERE k <= 100000;

	END
    PRINT 'Sample data inserted successfully.'
GO

create PROCEDURE InsertSampleData_DieuTri
AS
BEGIN
  WITH
	L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
	L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
	L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
	L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
	L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
	L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
	Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

	-- Thêm dữ liệu cho bảng DIEUTRI với MADIEUTRI và TENDIEUTRI từ 1 đến 1000000
	INSERT INTO DIEUTRI (MADIEUTRI, TENDIEUTRI)
	SELECT 
		k AS MADIEUTRI,
		N'Điều trị ' + CAST(k AS VARCHAR) AS TENDIEUTRI
	FROM Nums
	WHERE k <= 100000;

	END
    PRINT 'Sample data inserted successfully.'
GO

create PROCEDURE InsertSampleData_KeHoach_DieuTri
AS
BEGIN
	WITH
	L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
	L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
	L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
	L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
	L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
	L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
	Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

	-- Thêm dữ liệu cho bảng KEHOACH_DIEUTRI với KEHOACHDIEUTRI và DIEUTRI từ 1 đến 1000000
	INSERT INTO KEHOACH_DIEUTRI (KEHOACHDIEUTRI, DIEUTRI)
	SELECT 
		k AS KEHOACHDIEUTRI,
		k AS DIEUTRI
	FROM Nums
	WHERE k <= 100000;

	END
    PRINT 'Sample data inserted successfully.'
GO

create PROCEDURE InsertSampleData_ThongTinThanhToan
AS
BEGIN
	WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng THONGTINTHANHTOAN với MATHANHTOAN, NHASI, MABENHNHAN và các cột khác từ 1 đến 1000000
		INSERT INTO THONGTINTHANHTOAN (MATHANHTOAN, NHASI, MABENHNHAN, NGAYTHANHTOAN, NGAYGIAODICH, TONGTIENTHANHTOAN, TIENDATRA, TIENTHOI, LOAITHANHTOAN)
		SELECT 
			k AS MATHANHTOAN,
			k AS NHASI,
			k AS MABENHNHAN,
			'01/01/2022' AS NGAYTHANHTOAN,
			'01/01/2021' AS NGAYGIAODICH,
			null AS TONGTIENTHANHTOAN,
			k * 500 AS TIENDATRA,
			null AS TIENTHOI,
			CASE WHEN k % 2 = 0 THEN N'TIỀN MẶT' ELSE N'THANH TOÁN ONLINE' END AS LOAITHANHTOAN
		FROM Nums
		WHERE k <= 100000


    PRINT 'Sample data inserted successfully.'
END
GO

create PROCEDURE InsertSampleData_HoaDonDieuTri
AS
BEGIN
   WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng HOADONDIEUTRI với MAHOADON, MADIEUTRI và MOTA từ 1 đến 1000000
		INSERT INTO HOADONDIEUTRI (MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
		SELECT 
			k AS MAHOADON,
			k AS MADIEUTRI,
			N'Mô tả hóa đơn điều trị ' + CAST(k AS VARCHAR) AS MOTA,
			DATEADD(DAY, -FLOOR(RAND() * 36525), GETDATE()) AS NGAYDIEUTRI,
			k * 100 AS PHIDIEUTRI
		FROM Nums
		WHERE k <= 100000;

	

    PRINT 'Sample data inserted successfully.'
END
GO

create PROCEDURE InsertSampleData_LichLamViec
AS
BEGIN
	WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Thêm dữ liệu cho bảng LICHLAMVIEC với MALICH, MANHASI và các cột khác từ 1 đến 1000000
		INSERT INTO LICHLAMVIEC (MALICH, MANHASI, NGAY, GIOBATDAU, GIOKETTHUC)
		SELECT 
			CAST(k AS VARCHAR) AS MALICH,
			k AS MANHASI,
			'12/10/2024' AS NGAY,
			'08:30' AS GIOBATDAU,
			'17:30' AS GIOKETTHUC
		FROM Nums
		WHERE k <= 100000;



		PRINT 'Sample data inserted successfully.'
END
GO

CREATE PROCEDURE InsertSampleData_LichHen
AS
BEGIN
	
	WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Insert sample data into LICHHEN table with required columns
		INSERT INTO LICHHEN (MALICHHEN, THOIGIAN, GIOKETTHUC, NHASI, MABENHNHAN, GHICHU, TINHTRANG, THOIGIANYEUCAU, PHONG, NGAYHENYEUCAU)
		SELECT 
			k AS MALICHHEN,
			'09:30' AS THOIGIAN,
			'16:30' AS GIOKETTHUC,
			k AS NHASI,
			k AS MABENHNHAN,
			N'Ghi chú ' + CAST(k AS NVARCHAR(10)) AS GHICHU,
			N'Tình trạng ' + CAST(k AS NVARCHAR(10)) AS TINHTRANG,
			'12/10/2023' AS THOIGIANYEUCAU,
			k AS PHONG,
			'12/10/2024' NGAYHENYEUCAU
		FROM Nums
		WHERE k <= 100000;

		PRINT 'Sample data inserted successfully.'
END
GO

CREATE PROCEDURE InsertSampleData_LichTaiKham
AS
BEGIN
	
	WITH
		L0   AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)), -- 2^1
		L1   AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),       -- 2^2
		L2   AS (SELECT 1 AS c FROM L1 AS A CROSS JOIN L1 AS B),       -- 2^4
		L3   AS (SELECT 1 AS c FROM L2 AS A CROSS JOIN L2 AS B),       -- 2^8
		L4   AS (SELECT 1 AS c FROM L3 AS A CROSS JOIN L3 AS B),       -- 2^16
		L5   AS (SELECT 1 AS c FROM L4 AS A CROSS JOIN L4 AS B),       -- 2^32
		Nums AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L5)

		-- Insert sample data into LICHHEN table with required columns
		-- Thêm dữ liệu cho bảng LICHTAIKHAM với MATAIKHAM, NGAYCHIDINH, và GHICHU
        INSERT INTO LICHTAIKHAM (MATAIKHAM, NGAYCHIDINH, GHICHU)
        SELECT 
            k AS MATAIKHAM,
            DATEADD(DAY, k, GETDATE() + 1) AS NGAYCHIDINH,  -- Thêm 1 ngày để đảm bảo ngày lớn hơn hiện tại
            N'Ghi chú ' + CAST(k AS VARCHAR) AS GHICHU
        FROM Nums
        WHERE k <= 100000;


		PRINT 'Sample data inserted successfully.'
END
GO


SET IDENTITY_INSERT NGUOIDUNG ON
exec InsertSampleData
SET IDENTITY_INSERT NGUOIDUNG OFF
GO

SET IDENTITY_INSERT NHASI ON
exec InsertSampleData_NhaSi
SET IDENTITY_INSERT NHASI off
GO

SET IDENTITY_INSERT BENHNHAN ON
exec InsertSampleData_BenhNhan
SET IDENTITY_INSERT BENHNHAN Off
GO

exec InsertSampleData_ChiTietBenhNhan
GO

SET IDENTITY_INSERT THUOC ON
exec InsertSampleData_Thuoc
SET IDENTITY_INSERT THUOC OFF
GO

exec InsertSampleData_ChongChiDinh
GO

SET IDENTITY_INSERT KEHOACHDIEUTRI ON
exec InsertSampleData_KeHoachDieuTri
SET IDENTITY_INSERT KEHOACHDIEUTRI off
GO

SET IDENTITY_INSERT DONTHUOC ON
exec InsertSampleData_DonThuoc
SET IDENTITY_INSERT DONTHUOC OFF
GO


exec InsertSampleData_ChiTietDonThuoc
GO

exec InsertSampleData_Rang
GO

SET IDENTITY_INSERT DIEUTRI ON
exec InsertSampleData_DieuTri
SET IDENTITY_INSERT DIEUTRI off
GO


exec InsertSampleData_KeHoach_DieuTri
GO

SET IDENTITY_INSERT THONGTINTHANHTOAN ON
exec InsertSampleData_ThongTinThanhToan
SET IDENTITY_INSERT THONGTINTHANHTOAN OFF
GO

exec InsertSampleData_HoaDonDieuTri
GO

exec InsertSampleData_LichLamViec
GO

SET IDENTITY_INSERT LICHHEN ON
ALTER TABLE LICHHEN DISABLE TRIGGER TRIGGER_LICHHEN 
exec InsertSampleData_LichHen
ALTER TABLE LICHHEN ENABLE TRIGGER TRIGGER_LICHHEN 
SET IDENTITY_INSERT LICHHEN OFF
GO

exec InsertSampleData_LichTaiKham
go

-- SELECT * FROM NGUOIDUNG
-- select * from NHASI
-- SELECT * FROM BENHNHAN
-- select * from CHITIETHOSOBENHNHAN
-- SELECT * FROM THUOC
-- select * from KEHOACHDIEUTRI
-- select * from KEHOACH_DIEUTRI
-- select * from DONTHUOC
-- select * from CHITIETDONTHUOC
-- select * from RANG
-- select * from THONGTINTHANHTOAN
-- select * from HOADONDIEUTRI
-- select * from lichlamviec
-- select * from LICHHEN


-- delete from LICHHEN