USE QLNhaKhoa
-------------------------------------------------------------------------------------------------
DROP TRIGGER IF EXISTS TRIGGER_BN
DROP TRIGGER IF EXISTS TRIGGER_THONGTINTT_TONGTIEN
DROP TRIGGER IF EXISTS TRIGGER_THONGTINTT_TIENDATRA_DELETE
DROP TRIGGER IF EXISTS TRIGGER_THONGTINTT_TIENDATRA_UPDATE
DROP TRIGGER IF EXISTS TRIGGER_LICHHEN 
DROP TRIGGER IF EXISTS TRIGGER_TINHTUOI
DROP TRIGGER IF EXISTS TRIGGER_HSCTBN_INSERT
DROP TRIGGER IF EXISTS TRIGGER_HOADONDIEUTRI_INSERT
DROP TRIGGER IF EXISTS TRIGGER_HOADONDIEUTRI_DELETE
DROP TRIGGER IF EXISTS TRIGGER_HOADONDIEUTRI_UPDATE
DROP TRIGGER IF EXISTS TRIGGER_CHECK_ROLE_BACSI
DROP TRIGGER IF EXISTS TRIGGER_CHECK_ROLE_NHANVIEN
DROP TRIGGER IF EXISTS TRIGGER_CHECK_ROLE_QUANTRIVIEN
DROP TRIGGER IF EXISTS TRIGGER_LICHLAMVIEC
---------------------------------------- TẠO CÁC TRIGGER ----------------------------------------
--BENH NHAN
GO
CREATE TRIGGER TRIGGER_BN
ON BENHNHAN
FOR INSERT
AS
	BEGIN
    IF EXISTS (SELECT *
    FROM inserted I, BENHNHAN BN
    WHERE I.MABENHNHAN = BN.MABENHNHAN AND
        I.HOTEN LIKE '%[0-9]%')
				   BEGIN
        RAISERROR('HOTEN KHONG THE CHUA KY TU SO', 16, 1)--HỌ TÊN KHÔNG THỂ CÓ KÍ TỰ SỐ 
        ROLLBACK TRANSACTION
    END
    IF EXISTS (SELECT *
    FROM inserted I, BENHNHAN BN
    WHERE I.MABENHNHAN = BN.MABENHNHAN AND
        ISNUMERIC(I.SODIENTHOAI) = 0)
				   BEGIN
        RAISERROR('SODIENTHOAI KHONG THE CHUA CHU CAI', 16, 1)--SỐ ĐIỆN THOẠI KHÔNG THỂ CÓ CHỮ CÁI
        ROLLBACK TRANSACTION
    END
END
GO

--TRIGGER KHI THÊM MỚI LỊCH LÀM VIỆC
CREATE TRIGGER TRIGGER_LICHLAMVIEC 
ON LICHLAMVIEC
FOR INSERT
AS
    BEGIN
      IF EXISTS (SELECT * FROM INSERTED i WHERE i.GIOBATDAU > i.GIOKETTHUC)
      BEGIN
        RAISERROR('GIOBATDAU KHONG DUOC LON HON GIO KET THUC', 16, 1)
        ROLLBACK TRANSACTION
      END

        IF EXISTS (SELECT * FROM INSERTED i JOIN LICHLAMVIEC LLV ON i.NGAY = LLV.NGAY WHERE i.GIOBATDAU < LLV.GIOKETTHUC OR LLV.GIOBATDAU < i.GIOKETTHUC)
      BEGIN
        RAISERROR('LICH HEN DA CO TRONG CSDL', 16, 1)
        ROLLBACK TRANSACTION
      END
    END
GO

--THONGTINTHANHTOAN
---------------------------------------------------------------------------------
CREATE TRIGGER TRIGGER_THONGTINTT_TONGTIEN --TRIGGER CHO BẢNG THÔNG TIN THANH TOÁN ĐỂ TÍNH TỔNG TIỀN ĐIỀU TRỊ DỰA TRÊN BẢNG HÓA ĐƠN THANH TOÁN
ON THONGTINTHANHTOAN
FOR INSERT
AS
    BEGIN
    IF EXISTS (SELECT *
    FROM inserted I, THONGTINTHANHTOAN T
    WHERE I.MATHANHTOAN = T.MATHANHTOAN AND I.NGAYGIAODICH < I.NGAYTHANHTOAN) 
            BEGIN
        UPDATE T
                SET T.TONGTIENTHANHTOAN = 0
                FROM THONGTINTHANHTOAN T JOIN INSERTED I ON I.MATHANHTOAN = T.MATHANHTOAN

        UPDATE T2
                SET T2.TIENTHOI = 0
                FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MATHANHTOAN
        --PHẦN NÀY ĐỂ KIỂM TRA MỖI LẦN THÊM MỘT THÔNG TIN THANH TOÁN, ĐẢM BẢO PHẦN TIỀN THANH TOÁN TRONG BẢNG HỒ SƠ CHI TIẾT BỆNH NHÂN CŨNG ĐƯỢC UPDATE
        IF EXISTS (SELECT *
        FROM THONGTINTHANHTOAN T JOIN CHITIETHOSOBENHNHAN CTHS ON CTHS.MABENHNHAN = T.MABENHNHAN JOIN INSERTED I ON I.MATHANHTOAN = T.MATHANHTOAN)
                        BEGIN
            UPDATE CTHSBN
                            SET CTHSBN.DATHANHTOAN = CTHSBN.DATHANHTOAN + T.TONGDATRA
                            FROM CHITIETHOSOBENHNHAN CTHSBN JOIN (SELECT CTHSBN2.MABENHNHAN, SUM(i2.TIENDATRA) AS TONGDATRA
                FROM inserted i2 JOIN CHITIETHOSOBENHNHAN CTHSBN2 ON CTHSBN2.MABENHNHAN = i2.MABENHNHAN
                GROUP BY CTHSBN2.MABENHNHAN) AS T ON CTHSBN.MABENHNHAN = T.MABENHNHAN

        END
    END
        ELSE 
            BEGIN
        RAISERROR('NGAY THANH TOAN PHAI LON HON NGAY GIAO DICH', 16, 1)--SỐ ĐIỆN THOẠI KHÔNG THỂ CÓ CHỮ CÁI
        ROLLBACK TRANSACTION
    END
END
GO

CREATE TRIGGER TRIGGER_THONGTINTT_TIENDATRA_DELETE
ON THONGTINTHANHTOAN
FOR INSERT, DELETE
AS
BEGIN
    IF EXISTS (SELECT *
    FROM THONGTINTHANHTOAN T JOIN CHITIETHOSOBENHNHAN CTHS ON CTHS.MABENHNHAN = T.MABENHNHAN JOIN deleted D ON D.MATHANHTOAN = T.MATHANHTOAN)
                        BEGIN
        UPDATE CTHSBN
            SET CTHSBN.DATHANHTOAN = CTHSBN.DATHANHTOAN - T.TONGDATRA
            FROM CHITIETHOSOBENHNHAN CTHSBN JOIN (SELECT CTHSBN2.MABENHNHAN, SUM(D2.TIENDATRA) AS TONGDATRA
            FROM deleted D2 JOIN CHITIETHOSOBENHNHAN CTHSBN2 ON CTHSBN2.MABENHNHAN = D2.MABENHNHAN
            GROUP BY CTHSBN2.MABENHNHAN) AS T ON CTHSBN.MABENHNHAN = T.MABENHNHAN

    END
END
GO

CREATE TRIGGER TRIGGER_THONGTINTT_TIENDATRA_UPDATE
ON THONGTINTHANHTOAN
FOR UPDATE
AS
BEGIN
    IF UPDATE(TIENDATRA)  -- Check if the TIENDATRA column is being updated
    BEGIN
        -- Xóa giá trị tổng đã trả cũ
        UPDATE CTHSBN
            SET CTHSBN.DATHANHTOAN = CTHSBN.DATHANHTOAN - T.TONGDATRA
            FROM CHITIETHOSOBENHNHAN CTHSBN JOIN (SELECT CTHSBN2.MABENHNHAN, SUM(D2.TIENDATRA) AS TONGDATRA
            FROM deleted D2 JOIN CHITIETHOSOBENHNHAN CTHSBN2 ON CTHSBN2.MABENHNHAN = D2.MABENHNHAN
            GROUP BY CTHSBN2.MABENHNHAN) AS T ON CTHSBN.MABENHNHAN = T.MABENHNHAN 
        -- Thêm giá trị tổng đã trả mới
        UPDATE CTHSBN
            SET CTHSBN.DATHANHTOAN = CTHSBN.DATHANHTOAN + T.TONGDATRA
            FROM CHITIETHOSOBENHNHAN CTHSBN JOIN (SELECT CTHSBN2.MABENHNHAN, SUM(i2.TIENDATRA) AS TONGDATRA
            FROM inserted i2 JOIN CHITIETHOSOBENHNHAN CTHSBN2 ON CTHSBN2.MABENHNHAN = i2.MABENHNHAN
            GROUP BY CTHSBN2.MABENHNHAN) AS T ON CTHSBN.MABENHNHAN = T.MABENHNHAN
    END
END
GO



--TRIGGER KIỂM TRA LỊCH HẸN CÓ TRÙNG VỚI CÁC LỊCH KHÁC CỦA BỆNH NHÂN HOẶC BÁC SĨ KHÔNG
--KIỂM TRA THỜI GIAN TRONG LỊCH HẸN CÓ TRÙNG VỚI LỊCH LÀM VIỆC CỦA NHA SĨ KHÔNG
CREATE TRIGGER TRIGGER_LICHHEN 
ON LICHHEN
INSTEAD OF INSERT, UPDATE
AS
	BEGIN
    SET NOCOUNT ON

    IF EXISTS (SELECT * FROM inserted I INNER JOIN LICHHEN LH ON (I.MABENHNHAN = LH.MABENHNHAN OR I.NHASI = LH.NHASI) AND ((DATEDIFF(DAY, I.THOIGIAN, LH.GIOKETTHUC) > 0) OR (DATEDIFF(DAY, LH.THOIGIAN, I.GIOKETTHUC) < 0)) AND I.NGAYHENYEUCAU = LH.NGAYHENYEUCAU)
	    BEGIN
            RAISERROR('LICH HEN KHONG DUOC TRUNG VOI LICH CUA BENH NHAN HOAC NHA SI', 16, 1)--HỌ TÊN KHÔNG THỂ CÓ KÍ TỰ SỐ 
            ROLLBACK TRANSACTION
        END
    ELSE IF EXISTS (SELECT * FROM inserted I, LICHLAMVIEC LLV WHERE LLV.NGAY != I.NGAYHENYEUCAU OR LLV.GIOBATDAU > I.THOIGIAN OR LLV.GIOKETTHUC < I.GIOKETTHUC OR LLV.GIOBATDAU > I.GIOKETTHUC OR LLV.GIOKETTHUC < I.THOIGIAN)
        BEGIN
            RAISERROR('NHA SI KHONG LAM VIEC TRONG THOI GIAN NAY', 16, 1)--HỌ TÊN KHÔNG THỂ CÓ KÍ TỰ SỐ 
            ROLLBACK TRANSACTION 
        END
    ELSE 
        BEGIN
            INSERT INTO LICHHEN (MALICHHEN, THOIGIAN, GIOKETTHUC, NHASI, MABENHNHAN, THOIGIANYEUCAU, NGAYHENYEUCAU, PHONG, TINHTRANG, GHICHU)
            SELECT MALICHHEN, THOIGIAN, GIOKETTHUC, NHASI, MABENHNHAN, THOIGIANYEUCAU, NGAYHENYEUCAU, PHONG, TINHTRANG, GHICHU
            FROM inserted
        END
END
GO

--TÍNH TUỔI TRÊN BẢNG CHI TIẾT HSBN
CREATE TRIGGER TRIGGER_TINHTUOI
ON CHITIETHOSOBENHNHAN
FOR INSERT, UPDATE
AS
    BEGIN
    IF EXISTS (SELECT *
    FROM inserted I, BENHNHAN BN
    WHERE I.MABENHNHAN = BN.MABENHNHAN)
            BEGIN
        UPDATE CTHSBN
                SET CTHSBN.TUOI = DATEDIFF(YY, BN.NGAYSINH, GETDATE())
                FROM BENHNHAN BN JOIN CHITIETHOSOBENHNHAN CTHSBN ON CTHSBN.MABENHNHAN = BN.MABENHNHAN
    END
END
GO

--TÍNH TỔNG TIỀN ĐIỀU TRỊ TRÊN BẢNG CHITIETHOSOBENHNHAN
CREATE TRIGGER TRIGGER_HSCTBN_INSERT
ON CHITIETHOSOBENHNHAN
FOR INSERT
AS
    BEGIN

    UPDATE CTHSBN
        SET CTHSBN.TONGTIENDIEUTRI = 0
        FROM CHITIETHOSOBENHNHAN CTHSBN JOIN INSERTED I ON I.MABENHNHAN = CTHSBN.MABENHNHAN

    UPDATE CTHSBN
        SET CTHSBN.DATHANHTOAN = 0
        FROM CHITIETHOSOBENHNHAN CTHSBN JOIN INSERTED I ON I.MABENHNHAN = CTHSBN.MABENHNHAN
    END
GO





--UPDATE LẠI GIÁ TRỊ TỔNG TIỀN THANH TOÁN CỦA BẢNG THÔNG TIN THANH TOÁN MỖI KHI HÓA ĐƠN TƯƠNG ỨNG VỚI THANH TOÁN NÀY ĐƯỢC NHẬP
CREATE TRIGGER TRIGGER_HOADONDIEUTRI_INSERT
ON HOADONDIEUTRI
FOR INSERT
AS
    BEGIN
    --UPDATE LẠI GIÁ TRỊ TỔNG TIỀN CẦN THANH TOÁN TRONG THÔNG TIN THANH TOÁN LUÔN
    IF EXISTS (SELECT * FROM inserted I, HOADONDIEUTRI HD WHERE I.MAHOADON = HD.MAHOADON)
    BEGIN
        IF EXISTS (SELECT * FROM THONGTINTHANHTOAN T JOIN HOADONDIEUTRI HD ON HD.MAHOADON = T.MATHANHTOAN JOIN INSERTED I ON I.MAHOADON = T.MATHANHTOAN)
            BEGIN
                UPDATE T
                SET T.TONGTIENTHANHTOAN = T.TONGTIENTHANHTOAN + TONGTHANHTOAN
                FROM THONGTINTHANHTOAN T JOIN (SELECT i.MAHOADON, SUM(i.PHIDIEUTRI) AS TONGTHANHTOAN
                FROM inserted i
                GROUP BY i.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN
             END
    END
    --UPDATE LẠI GIÁ TRỊ TỔNG TIỀN CẦN THANH TOÁN TRONG HỒ SƠ CHI TIẾT BỆNH NHÂN LUÔN
    IF EXISTS (SELECT * FROM THONGTINTHANHTOAN T JOIN CHITIETHOSOBENHNHAN CTHS ON CTHS.MABENHNHAN = T.MABENHNHAN JOIN INSERTED I ON T.MATHANHTOAN = I.MAHOADON)
        BEGIN
        --O DAY
            UPDATE CTHSBN
            SET CTHSBN.TONGTIENDIEUTRI = CTHSBN.TONGTIENDIEUTRI + TONGTHANHTOAN
            FROM CHITIETHOSOBENHNHAN CTHSBN JOIN THONGTINTHANHTOAN T ON T.MABENHNHAN = CTHSBN.MABENHNHAN
            JOIN (SELECT i.MAHOADON, SUM(i.PHIDIEUTRI) AS TONGTHANHTOAN
            FROM inserted i
            GROUP BY i.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN
        END

    -- TỰ ĐỘNG TÍNH TIỀN THỐI DỰA TRÊN TIỀN CẦN THANH TOÁN VÀ TIỀN ĐÃ TRẢ NẾU TIỀN ĐÃ TRẢ LỚN HƠN TIỀN THANH TOÁN

    UPDATE T2
        SET T2.TIENTHOI = T2.TIENDATRA - T2.TONGTIENTHANHTOAN
        FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MAHOADON
        WHERE T2.TONGTIENTHANHTOAN < T2.TIENDATRA


    UPDATE T2
        SET T2.TIENTHOI = 0
        FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MAHOADON
        WHERE T2.TONGTIENTHANHTOAN >= T2.TIENDATRA

END
GO

--UPDATE LẠI GIÁ TRỊ TỔNG TIỀN THANH TOÁN CỦA BẢNG THÔNG TIN THANH TOÁN MỖI KHI HÓA ĐƠN TƯƠNG ỨNG VỚI THANH TOÁN NÀY ĐƯỢC NHẬP
CREATE TRIGGER TRIGGER_HOADONDIEUTRI_DELETE
ON HOADONDIEUTRI
FOR DELETE
AS
    BEGIN
    --UPDATE LẠI GIÁ TRỊ TỔNG TIỀN CẦN THANH TOÁN TRONG THÔNG TIN THANH TOÁN LUÔN
    IF EXISTS (SELECT * FROM deleted D, HOADONDIEUTRI HD WHERE D.MAHOADON = HD.MAHOADON)
        BEGIN
            IF EXISTS (SELECT * FROM THONGTINTHANHTOAN T JOIN HOADONDIEUTRI HD ON HD.MAHOADON = T.MATHANHTOAN JOIN deleted D ON D.MAHOADON = T.MATHANHTOAN)
                BEGIN
                    UPDATE T
                    SET T.TONGTIENTHANHTOAN = T.TONGTIENTHANHTOAN - TONGTHANHTOAN
                    FROM THONGTINTHANHTOAN T JOIN (SELECT D.MAHOADON, SUM(D.PHIDIEUTRI) AS TONGTHANHTOAN
                    FROM deleted D
                    GROUP BY D.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN
                END
        END
    --UPDATE LẠI GIÁ TRỊ TỔNG TIỀN CẦN THANH TOÁN TRONG HỒ SƠ CHI TIẾT BỆNH NHÂN LUÔN
    IF EXISTS (SELECT * FROM THONGTINTHANHTOAN T JOIN CHITIETHOSOBENHNHAN CTHS ON CTHS.MABENHNHAN = T.MABENHNHAN JOIN deleted D ON T.MATHANHTOAN = D.MAHOADON)
        BEGIN
            --O DAY
            UPDATE CTHSBN
            SET CTHSBN.TONGTIENDIEUTRI = CTHSBN.TONGTIENDIEUTRI - TONGTHANHTOAN
            FROM CHITIETHOSOBENHNHAN CTHSBN JOIN THONGTINTHANHTOAN T ON T.MABENHNHAN = CTHSBN.MABENHNHAN
            JOIN (SELECT D.MAHOADON, D.PHIDIEUTRI AS TONGTHANHTOAN
            FROM deleted D
            ) AS HD ON HD.MAHOADON = T.MATHANHTOAN
        END

    -- TỰ ĐỘNG TÍNH TIỀN THỐI DỰA TRÊN TIỀN CẦN THANH TOÁN VÀ TIỀN ĐÃ TRẢ NẾU TIỀN ĐÃ TRẢ LỚN HƠN TIỀN THANH TOÁN

    UPDATE T2
        SET T2.TIENTHOI = T2.TIENDATRA - T2.TONGTIENTHANHTOAN
        FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MAHOADON
        WHERE T2.TONGTIENTHANHTOAN < T2.TIENDATRA


    UPDATE T2
        SET T2.TIENTHOI = 0
        FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MAHOADON
        WHERE T2.TONGTIENTHANHTOAN >= T2.TIENDATRA

END
GO

CREATE TRIGGER TRIGGER_HOADONDIEUTRI_UPDATE
ON HOADONDIEUTRI
FOR UPDATE
AS
    BEGIN
    --UPDATE LẠI GIÁ TRỊ TỔNG TIỀN CẦN THANH TOÁN TRONG THÔNG TIN THANH TOÁN LUÔN
    IF EXISTS (SELECT * FROM deleted D, HOADONDIEUTRI HD WHERE D.MAHOADON = HD.MAHOADON)
        BEGIN
            IF EXISTS (SELECT * FROM THONGTINTHANHTOAN T JOIN HOADONDIEUTRI HD ON HD.MAHOADON = T.MATHANHTOAN JOIN deleted D ON D.MAHOADON = T.MATHANHTOAN)
                BEGIN
                    --XÓA CÁI CŨ
                    UPDATE T
                    SET T.TONGTIENTHANHTOAN = T.TONGTIENTHANHTOAN - TONGTHANHTOAN
                    FROM THONGTINTHANHTOAN T JOIN (SELECT D.MAHOADON, SUM(D.PHIDIEUTRI) AS TONGTHANHTOAN
                    FROM deleted D
                    GROUP BY D.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN
                    --UPDATE LẠI CÁI MỚI
                    UPDATE T
                    SET T.TONGTIENTHANHTOAN = T.TONGTIENTHANHTOAN + TONGTHANHTOAN
                    FROM THONGTINTHANHTOAN T JOIN (SELECT I.MAHOADON, SUM(I.PHIDIEUTRI) AS TONGTHANHTOAN
                    FROM inserted I
                    GROUP BY I.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN
                END
        END
    --UPDATE LẠI GIÁ TRỊ TỔNG TIỀN CẦN THANH TOÁN TRONG HỒ SƠ CHI TIẾT BỆNH NHÂN LUÔN
    IF EXISTS (SELECT * FROM THONGTINTHANHTOAN T JOIN CHITIETHOSOBENHNHAN CTHS ON CTHS.MABENHNHAN = T.MABENHNHAN JOIN deleted D ON T.MATHANHTOAN = D.MAHOADON)
        BEGIN
            --XOA CAI CU
            UPDATE CTHSBN
            SET CTHSBN.TONGTIENDIEUTRI = CTHSBN.TONGTIENDIEUTRI - TONGTHANHTOAN
            FROM CHITIETHOSOBENHNHAN CTHSBN JOIN THONGTINTHANHTOAN T ON T.MABENHNHAN = CTHSBN.MABENHNHAN
            JOIN (SELECT D.MAHOADON, SUM(D.PHIDIEUTRI) AS TONGTHANHTOAN
            FROM deleted D
            GROUP BY D.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN

            --THEM CAI MOI
            UPDATE CTHSBN
            SET CTHSBN.TONGTIENDIEUTRI = CTHSBN.TONGTIENDIEUTRI + TONGTHANHTOAN
            FROM CHITIETHOSOBENHNHAN CTHSBN JOIN THONGTINTHANHTOAN T ON T.MABENHNHAN = CTHSBN.MABENHNHAN
            JOIN (SELECT I.MAHOADON, SUM(I.PHIDIEUTRI) AS TONGTHANHTOAN
            FROM inserted I
            GROUP BY I.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN
        END

    -- TỰ ĐỘNG TÍNH TIỀN THỐI DỰA TRÊN TIỀN CẦN THANH TOÁN VÀ TIỀN ĐÃ TRẢ NẾU TIỀN ĐÃ TRẢ LỚN HƠN TIỀN THANH TOÁN

    UPDATE T2
        SET T2.TIENTHOI = T2.TIENDATRA - T2.TONGTIENTHANHTOAN
        FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MAHOADON
        WHERE T2.TONGTIENTHANHTOAN < T2.TIENDATRA


    UPDATE T2
        SET T2.TIENTHOI = 0
        FROM THONGTINTHANHTOAN T2 JOIN inserted I ON T2.MATHANHTOAN = I.MAHOADON
        WHERE T2.TONGTIENTHANHTOAN >= T2.TIENDATRA

END
GO

--TRIGGER KIỂM TRA KHI THÊM MỘT NGƯỜI DÙNG
CREATE TRIGGER TRIGGER_CHECK_ROLE_BACSI
ON NHASI
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
    FROM inserted I
        JOIN NGUOIDUNG ND ON ND.MANGUOIDUNG = I.MABACSI
    WHERE ND.ROLES NOT IN (N'NHA SĨ')
    )
    BEGIN
        RAISERROR('ROLE CUA NGUOI DUNG KHONG HOP LE', 16, 1)
        ROLLBACK TRANSACTION
    END
END
GO

CREATE TRIGGER TRIGGER_CHECK_ROLE_NHANVIEN
ON NHANVIEN
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS ( SELECT 1 
                FROM inserted I JOIN NGUOIDUNG ND ON ND.MANGUOIDUNG = I.MANHANVIEN
                WHERE ND.ROLES NOT IN (N'NHÂN VIÊN'))
        BEGIN
            RAISERROR('ROLE CUA NGUOI DUNG KHONG HOP LE', 16, 1)
            ROLLBACK TRANSACTION
        END
END
GO

CREATE TRIGGER TRIGGER_CHECK_ROLE_QUANTRIVIEN
ON QUANTRIVIEN
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
    FROM inserted I
        JOIN NGUOIDUNG ND ON ND.MANGUOIDUNG = I.MAQTV
    WHERE ND.ROLES NOT IN (N'QUẢN TRỊ VIÊN')
    )
    BEGIN
        RAISERROR('ROLE CUA NGUOI DUNG KHONG HOP LE', 16, 1)
        ROLLBACK TRANSACTION
    END
END
GO


-- SELECT * FROM CHITIETHOSOBENHNHAN WHERE MABENHNHAN = '000693'
-- SELECT * FROM THONGTINTHANHTOAN WHERE MABENHNHAN = '000693'
-- SELECT * FROM HOADONDIEUTRI WHERE WHERE MABENHNHAN = '000693'
-- SELECT * FROM DIEUTRI

-- SET IDENTITY_INSERT NGUOIDUNG ON
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('1', 'User 2', 'username 1', 'password 1', '01/01/2001', '123', '098122323', N'Nhân viên')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('2', 'User 2', 'username 2', 'password 2', '01/01/2001', '123', '098122323', N'Nhân viên')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('3', 'User 3', 'username 3', 'password 3', '01/01/2001', '123', '098122323', N'Nhân viên')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('4', 'User 4', 'username 4', 'password 4', '01/01/2001', '123', '098122323', N'Nhân viên')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('5', 'User 5', 'username 5', 'password 5', '01/01/2001', '123', '098122323', N'Nhân viên')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('6', 'User 6', 'username 6', 'password 6', '01/01/2001', '123', '098122323', N'Nhân viên')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('7', 'User 7', 'username 7', 'password 7', '01/01/2001', '123', '098122323', N'Nhân viên')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('8', 'User 8', 'username 8', 'password 8', '01/01/2001', '123', '098122323', N'Nhân viên')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('9', 'User 9', 'username 9', 'password 9', '01/01/2001', '123', '098122323', N'Nhân viên')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('10', 'User 10', 'username 10', 'password 10', '01/01/2001', '123', '098122323', N'Nhân viên')
-- SET IDENTITY_INSERT NGUOIDUNG OFF


-- SET IDENTITY_INSERT NGUOIDUNG ON
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('11', 'User 2', 'username 1', 'password 1', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('12', 'User 2', 'username 2', 'password 2', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('13', 'User 3', 'username 3', 'password 3', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('14', 'User 4', 'username 4', 'password 4', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('15', 'User 5', 'username 5', 'password 5', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('16', 'User 6', 'username 6', 'password 6', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('17', 'User 7', 'username 7', 'password 7', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('18', 'User 8', 'username 8', 'password 8', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('19', 'User 9', 'username 9', 'password 9', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- INSERT INTO NGUOIDUNG (MANGUOIDUNG, TENDANGNHAP, MATKHAU, TENNGUOIDUNG, NGAYSINH, DIACHI, SODIENTHOAI, ROLES)
-- values ('20', 'User 10', 'username 10', 'password 10', '01/01/2001', '123', '098122323', N'Nha sĩ')
-- SET IDENTITY_INSERT NGUOIDUNG OFF


-- SET IDENTITY_INSERT nhasi ON
-- insert into NHASI (MABACSI, CHUYENMON, KINHNGHIEM)
-- values ('11', 'chuyen mon 1', 'kinh nghiem 1')
-- insert into NHASI (MABACSI, CHUYENMON, KINHNGHIEM)
-- values ('12', 'chuyen mon 2', 'kinh nghiem 2')
-- insert into NHASI (MABACSI, CHUYENMON, KINHNGHIEM)
-- values ('13', 'chuyen mon 3', 'kinh nghiem 3')
-- insert into NHASI (MABACSI, CHUYENMON, KINHNGHIEM)
-- values ('14', 'chuyen mon 4', 'kinh nghiem 4')
-- insert into NHASI (MABACSI, CHUYENMON, KINHNGHIEM)
-- values ('15', 'chuyen mon 5', 'kinh nghiem 5')
-- insert into NHASI (MABACSI, CHUYENMON, KINHNGHIEM)
-- values ('16', 'chuyen mon 6', 'kinh nghiem 6')
-- SET IDENTITY_INSERT NHASI off

-- SET IDENTITY_INSERT NHANVIEN ON
-- insert into NHANVIEN(MANHANVIEN, PHONGBAN)
-- values ('1', 'PHONG BAN 1')
-- insert into NHANVIEN(MANHANVIEN, PHONGBAN)
-- values ('2', 'PHONG BAN 2')
-- insert into NHANVIEN(MANHANVIEN, PHONGBAN)
-- values ('3', 'PHONG BAN 3')
-- insert into NHANVIEN(MANHANVIEN, PHONGBAN)
-- values ('4', 'PHONG BAN 4')
-- insert into NHANVIEN(MANHANVIEN, PHONGBAN)
-- values ('5', 'PHONG BAN 5')
-- insert into NHANVIEN(MANHANVIEN, PHONGBAN)
-- values ('6', 'PHONG BAN 6')
-- insert into NHANVIEN(MANHANVIEN, PHONGBAN)
-- values ('7', 'PHONG BAN 7')
-- insert into NHANVIEN(MANHANVIEN, PHONGBAN)
-- values ('8', 'PHONG BAN 8')
-- SET IDENTITY_INSERT NHANVIEN off


-- SET IDENTITY_INSERT BENHNHAN ON
-- insert into BENHNHAN(MABENHNHAN, HOTEN, SODIENTHOAI , DIACHI, EMAIL, NGAYSINH, NHASI)
-- values (1, 'BENH NHAN', '0123456', 'DIA CHI 1', 'EMAIL 1', '01/03/2003', NULL)
-- insert into BENHNHAN(MABENHNHAN, HOTEN, SODIENTHOAI , DIACHI, EMAIL, NGAYSINH, NHASI)
-- values (2, 'BENH NHAN', '0123456', 'DIA CHI 1', 'EMAIL 1', '01/03/2003', NULL)
-- insert into BENHNHAN(MABENHNHAN, HOTEN, SODIENTHOAI , DIACHI, EMAIL, NGAYSINH, NHASI)
-- values (3, 'BENH NHAN', '0123456', 'DIA CHI 1', 'EMAIL 1', '01/03/2003', NULL)
-- insert into BENHNHAN(MABENHNHAN, HOTEN, SODIENTHOAI , DIACHI, EMAIL, NGAYSINH, NHASI)
-- values (4, 'BENH NHAN', '0123456', 'DIA CHI 1', 'EMAIL 1', '01/03/2003', NULL)
-- insert into BENHNHAN(MABENHNHAN, HOTEN, SODIENTHOAI , DIACHI, EMAIL, NGAYSINH, NHASI)
-- values (5, 'BENH NHAN', '0123456', 'DIA CHI 1', 'EMAIL 1', '01/03/2003', NULL)
-- insert into BENHNHAN(MABENHNHAN, HOTEN, SODIENTHOAI , DIACHI, EMAIL, NGAYSINH, NHASI)
-- values (6, 'BENH NHAN', '0123456', 'DIA CHI 1', 'EMAIL 1', '01/03/2003', NULL)
-- insert into BENHNHAN(MABENHNHAN, HOTEN, SODIENTHOAI , DIACHI, EMAIL, NGAYSINH, NHASI)
-- values (7, 'BENH NHAN', '0123456', 'DIA CHI 1', 'EMAIL 1', '01/03/2003', NULL)
-- insert into BENHNHAN(MABENHNHAN, HOTEN, SODIENTHOAI , DIACHI, EMAIL, NGAYSINH, NHASI)
-- values (8, 'BENH NHAN', '0123456', 'DIA CHI 1', 'EMAIL 1', '01/03/2003', NULL)
-- insert into BENHNHAN(MABENHNHAN, HOTEN, SODIENTHOAI , DIACHI, EMAIL, NGAYSINH, NHASI)
-- values (9, 'BENH NHAN', '0123456', 'DIA CHI 1', 'EMAIL 1', '01/03/2003', NULL)
-- SET IDENTITY_INSERT BENHNHAN off



-- insert into CHITIETHOSOBENHNHAN(MABENHNHAN, TUOI, GIOITINH , TONGTIENDIEUTRI, DATHANHTOAN, SUCKHOERANGMIENG, TINHTRANGDIUNG)
-- values (2, NULL, 'Nam', NULL, NULL, 'KHOE', 'KHONG KHOE')

-- SET IDENTITY_INSERT THONGTINTHANHTOAN ON
-- INSERT INTO THONGTINTHANHTOAN(MATHANHTOAN, NHASI, MABENHNHAN, NGAYTHANHTOAN, NGAYGIAODICH, TONGTIENTHANHTOAN, TIENDATRA, TIENTHOI, LOAITHANHTOAN)
-- VALUES (1, 11, 1, '04/03/2021', '03/01/2020', null, 500, null, N'TIỀN MẶT')
-- SET IDENTITY_INSERT THONGTINTHANHTOAN off

-- SET IDENTITY_INSERT DIEUTRI ON
-- INSERT INTO DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES(1, 'Dieu tri 1')
-- INSERT INTO DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES(2, 'Dieu tri 2')
-- INSERT INTO DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES(3, 'Dieu tri 3')
-- INSERT INTO DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES(4, 'Dieu tri 4')
-- INSERT INTO DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES(5, 'Dieu tri 5')
-- INSERT INTO DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES(6, 'Dieu tri 6')
-- INSERT INTO DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES(7, 'Dieu tri 7')
-- SET IDENTITY_INSERT DIEUTRI off

-- INSERT INTO HOADONDIEUTRI(MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
-- VALUES(1, 1, 'HOA DON 1', '04/10/2020', 1000)

-- update THONGTINTHANHTOAN
-- SET TIENDATRA = 250
-- WHERE MATHANHTOAN = 1

-- DELETE FROM HOADONDIEUTRI WHERE MAHOADON = 1 AND MADIEUTRI = 1

-- select * from THONGTINTHANHTOAN
-- select * from CHITIETHOSOBENHNHAN
-- SELECT * FROM HOADONDIEUTRI



-- UPDATE THONGTINTHANHTOAN
-- SET TONGTIENTHANHTOAN = TONGTIENTHANHTOAN + 100
-- FROM THONGTINTHANHTOAN TT WHERE TT.MATHANHTOAN = 1
-- SELECT * FROM THONGTINTHANHTOAN TT WHERE TT.MATHANHTOAN = 1
-- SELECT * FROM HOADONDIEUTRI HD JOIN THONGTINTHANHTOAN TT ON TT.MATHANHTOAN = HD.MAHOADON WHERE HD.MAHOADON = 1 AND MADIEUTRI = 1

-- SELECT * FROM HOADONDIEUTRI WHERE MAHOADON = 1

-- insert into LICHLAMVIEC(MALICH, MANHASI, NGAY , GIOBATDAU, GIOKETTHUC)
-- values ('1', 11, '01/03/2003', '08:30', '09:30')







-- exec Proc_ThemBenhNhan 
--     @HoTen = "Benh nhan 1",
--     @SoDienThoai = "1234556a",
--     @DiaChi = "123 bach dang",
--     @Email = "email 1",
--     @NgaySinh = '03/02/2001',
--     @NhaSi = null





-- INSERT DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES ('001', 'E')

-- SELECT TOP 1 * FROM NHASI

-- INSERT DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES ('005', 'E')
-- INSERT DIEUTRI(MADIEUTRI, TENDIEUTRI)
-- VALUES ('002', 'E')
-- INSERT INTO HOADONDIEUTRI(MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
-- VALUES ('606762', '005', 'afhbd', '21/12/2022', 4000)
-- INSERT INTO HOADONDIEUTRI(MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
-- VALUES ('606762', '002', 'DEO CO MO TA', '21/12/2022', 10)
-- INSERT INTO THONGTINTHANHTOAN(MATHANHTOAN,NHASI,MABENHNHAN,NGAYTHANHTOAN,NGAYGIAODICH,TONGTIENTHANHTOAN,TIENDATRA,TIENTHOI,LOAITHANHTOAN)
-- VALUES ('606763', '170902', '871991', '31/05/2004', '13/05/1986',100,200,100,'THANH TOÁN ONLINE')
-- INSERT INTO HOADONDIEUTRI(MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
-- VALUES ('606763', '005', 'DEO CO MO TA', '21/12/2022', 4000)
-- INSERT INTO HOADONDIEUTRI(MAHOADON, MADIEUTRI, MOTA, NGAYDIEUTRI, PHIDIEUTRI)
-- VALUES ('606763', '002', 'DEO CO MO TA', '21/12/2022', 10)
-- UPDATE T
-- SET T.TONGTIENTHANHTOAN = 6
-- FROM THONGTINTHANHTOAN T

-- UPDATE T
-- SET T.TONGTIENTHANHTOAN = T.TONGTIENTHANHTOAN + TONGTHANHTOAN
-- FROM THONGTINTHANHTOAN T JOIN (SELECT i.MAHOADON, SUM(i.PHIDIEUTRI) AS TONGTHANHTOAN
--                                                     FROM HOADONDIEUTRI i
--                                                     GROUP BY i.MAHOADON) AS HD ON HD.MAHOADON = T.MATHANHTOAN
-- SELECT * FROM THONGTINTHANHTOAN       