-- Create filegroups (if not already created)
ALTER DATABASE YourDatabase
ADD FILEGROUP BEFORE_2023;

ALTER DATABASE YourDatabase
ADD FILEGROUP BETWEEN_2023_AND_2024;

ALTER DATABASE YourDatabase
ADD FILEGROUP ON_OR_AFTER_2024;

-- Create a partition function
CREATE PARTITION FUNCTION PF_THONGTIN_THANHTOAN (DATE)
AS RANGE LEFT FOR VALUES ('20230101', '20240101');

-- Create a partition scheme
CREATE PARTITION SCHEME PS_THONGTIN_THANHTOAN
AS PARTITION PF_THONGTIN_THANHTOAN
TO ([BEFORE_2023], [BETWEEN_2023_AND_2024], [ON_OR_AFTER_2024]);

-- Alter the THONGTINTHANHTOAN table to use the partition scheme
ALTER TABLE THONGTINTHANHTOAN
DROP CONSTRAINT PK_THONGTINTT;

ALTER TABLE THONGTINTHANHTOAN
ADD CONSTRAINT PK_THONGTINTT
PRIMARY KEY NONCLUSTERED (MATHANHTOAN, NGAYGIAODICH)
ON PS_THONGTIN_THANHTOAN(NGAYGIAODICH);

-- Add a clustered index on the partitioning column
CREATE CLUSTERED INDEX CI_THONGTINTHANHTOAN_NGAYGIAODICH
ON THONGTINTHANHTOAN (NGAYGIAODICH)
ON PS_THONGTIN_THANHTOAN(NGAYGIAODICH);

-- Add a nonclustered index on another column (replace COLUMN_NAME with the actual column name)
CREATE NONCLUSTERED INDEX IX_THONGTINTHANHTOAN_ANOTHER_COLUMN
ON THONGTINTHANHTOAN (COLUMN_NAME);
